### ISSUE TITLE
Crash in Safari

### ISSUE THREAD

**Issue by andricor** [eldinor/babylon-wordpress-plugin#11]
Hi there!

When opening a 3d model embedded with the babylon wordpress plugin on the safari browser, it crashes.
Now sure if this is already a known issue.

Thanks

**Comment by eldinor** [comment]
You may change the script URL at the line 85:

`    wp_enqueue_script( 'babylon-viewer', esc_url_raw( 'https://cdn.babylonjs.com/viewer/babylon.viewer.js' ), array(), null, true );`

change to 

`    wp_enqueue_script( 'babylon-viewer', esc_url_raw( 'https://preview.babylonjs.com/viewer/babylon.viewer.js' ), array(), null, true );`

I think I'll add the possibility to change it directly in the plugin settings in the next versions.
