### ISSUE TITLE
list of all options

### ISSUE THREAD

**Issue by alFrame** [eldinor/babylon-wordpress-plugin#12]
First, thank you for this plugin! And I apologize in advance if this is a stupid question, or not the place o ask...

I am a typical 3D artist with some extended WordPress knowledge that found your plugin. So not a programmer. It totally works and I like it a lot. But I get stuck at the configuration. I have to say that I think it would be nice if the settings from the scene, that was created with the sandbox editor, would simply be used to display the scene on a WordPress site. When I drag the file onto a new sandbox, all settings are used. So if I set limits on the camera, they are used in the new sandbox. Would that not be the easiest way also for a plugin? Or am I missing something? Off course the local settings in html could be used to overwrite the ones in the scene for people who want that. But if nothing is defined, just the file loaded, it should use the scenes settings.

I do understand from looking at the actual BabylonJS code here: https://github.com/BabylonJS/Babylon.js/blob/master/Viewer/src/configuration/interfaces/cameraConfiguration.ts that I can set the position by setting: <position> **x**="3" **y**="3" **z**="3"</position> Because I can see in the code that the position anticipates 3 numbers tagged with x, y and z.

But I cannot figure out how to set the minZ (also know as lowerRadiusLimit as it seems). The code reads: "minZ?: number;". So I know that a number is anticipated

I tried to set it at the camera opening tag: <camera lowerRadiusLimit="4"> and also <camera minZ="4">

To no avail.

Then I tried to set it in the html like the position. But that didn't make sense, because it ended up like this: <lowerRadiusLimit="4"></lowerRadiusLimit> My gut tells me that it should be something like: <lowerRadiusLimit (something-goes-here)="4"></lowerRadiusLimit>

I don't seem to be capable of converting the code that is described here to the syntax the plugin is expecting:  https://doc.babylonjs.com/extensions/babylonViewer/configuringViewer#configuring-the-viewer

I guess it would really really help to have a full list of configuration examples. Or maybe that exists and I am simply not able to find it.

Here is the blog post I am working on: https://www.blog.fullframestudios.ch/babylonjs/

And I am almost done. All I would like, at this point, is to set the minimum and maximum of zoom and maybe also set the lower beta limit as I set it in the sandbox editor.

**Comment by eldinor** [comment]
Let me know if you still have any problems :)
The problems which you described relates more to the viewer than to the plugin.
Hopefully it is always possible to solve them at Babylon forum - https://forum.babylonjs.com/

**Comment by alFrame** [comment]
I first had to remember what I was talking about. But thanks for chiming in I guess...
