### ISSUE TITLE
Short Code from hook not working

### ISSUE THREAD

**Issue by Maverick1983** [eldinor/babylon-wordpress-plugin#14]
If I use hook for write short code
`do_shortcode('[babylon]'.$object3D.'[/babylon]');`
will be write the code on html page, but nothing happening. If I write short code direct on the page and use hook, both working.

**Comment by eldinor** [comment]
Probably this is because shortcode template is a kind of hook itself?

**Comment by eldinor** [comment]
Closed before the next update.
